### ISSUE TITLE
Trouble using with Create React App

### ISSUE THREAD

**Issue by Ulimn** [ljosberinn/eslint-config-galex#272]
I have a React app bootstrapped with Create React App. I added this eslint config as per the instructions. 
Upon running running eslint on the src directory, I got a lot of errors on files that come by default from CRA (eg.: `serviceWorker.ts`).

How should this be handled? I tried adding `react-app` to the extensions in the eslint config, but it introduced additional problems and in the end it did not help.

**Comment by ljosberinn** [comment]
Hi, thank you for reaching out!

A few errors are definitely expected, I started a `create-react-app@latest` just now and (after removing `package.json` > `eslintConfig` key) had e.g. these:
- `App.js` - `import/no-default-export`
- `reportWebVitals.js` - `import/no-default-export` as well as `promise/catch-or-return`

I don't have a  `serviceWorker.ts` file as they iirc removed shipping a service worker by default in 4.0 so I can't speak in this regard - however the last time I checked, most issues there were actual issues (e.g. not catching errors on promises), so these are still relevant.

I wouldn't recommend using `eslint-config-react-app`, neither within CRA nor in general, as their dependencies are notoriously outdated, this was actually one of my reasons to create this config.  You can't upgrade the config it comes with, because it's a peer dependency to `react-scripts`, so you'd have to eject or tinker with `craco` or similar (if that works for eslint; haven't tried). Apart from that, it comes with some practices I definitely disagree with (default exports, exhaustive-deps as warning).

**Comment by Ulimn** [comment]
Thank you for the reply! You are right, they removed it - I wasn't aware, sorry. 

I used `@chakra-ui/typescript` template to create the project and it still has a `serviceWorker.ts`. I will move my project files to a normal CRA and add chakra manually.

**Comment by ljosberinn** [comment]
Please let me know when/if you run into issues in this scenario :)
